version: '3.1'
services:
  wordpress:
    container_name: wordpress
    image: wordpress
    ports:
      - 80:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: 54.204.197.241
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: holaquemas
      WORDPRESS_DB_NAME: db1
    volumes:
      - /home/ubuntu/Miau:/var/www/html
